### PR TITLE
Use explicit error-chain version

### PR DESCRIPTION
**Pull request by killercup**
'Cause wildcard dependencies are Semver's version of Satan.

### CODE REVIEW

**Comment by JustAPerson** [comment]
Have you noticed this commit removes a lot whitespace? Seems like a mistake.

**Comment by killercup** [comment]
Oh? I made it via the web interface. That's not cool.

Can you replace the star and ignore/close this PR? :)

Jason Priest <notifications@github.com> schrieb am Di. 21. März 2017 um
04:10:

**Comment by stevedonovan** [comment]
I was just looking at https://github.com/tafia/quick-protobuf/issues/58, so I'm totally with you on this one!

**Comment by stevedonovan** [comment]
I see the problem - I added some whitespace. In fact, I'm going to nail `error-chain` down to `0.8.1' since 
'0.10' is exactly the one with the problem described in that issue.  Let me fix this manually then.

**Pull request closed without merging**
