### PR TITLE
Fix typo in Basics code block

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by stevedonovan** [comment]
Thanks! I _really_ need to be able to compile all the code. Most of the code is `rustc` tested, but the little one-liners are the problem.

**Comment by killercup** [comment]
This is something that mdbook can do btw!

Steve J Donovan <notifications@github.com> schrieb am Di. 21. März 2017 um
09:47:

**Comment by stevedonovan** [comment]
Sure, and in fact that's exactly the tool I'm starting to use. Unfortunately it fails very silently - I'll ask around.

**Comment by stevedonovan** [comment]
It's working, and I see exactly what you mean....

**Pull request merged**
